Repository woowa-techcamp-2022/android-banchan-09, pull requests merged in 2022-08, with the labels that each got.

#4 Feat/dependency injection
  app/build.gradle
  app/src/main/java/com/woowa/banchan/data/local/BanchanDataBase.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderItemDao.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/RecentDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/Cart.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/Order.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderItem.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/Recent.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/remote/datasource/food/FoodDataSource.kt
  app/src/main/java/com/woowa/banchan/data/remote/datasource/food/FoodDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/remote/repository/FoodRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/remote/service/BanchanService.kt
  app/src/main/java/com/woowa/banchan/di/DataBaseModule.kt
  app/src/main/java/com/woowa/banchan/di/NetworkModule.kt
  app/src/main/java/com/woowa/banchan/domain/repository/CartRepository.kt
  app/src/main/java/com/woowa/banchan/domain/repository/FoodRepository.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
  app/src/main/java/com/woowa/banchan/domain/repository/RecentRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/interface/GetDetailFoodUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/interface/GetTotalFoodUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/interface/DeleteFoodFromCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/interface/InsertFoodToCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/interface/UpdateFoodCheckStateUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/interface/UpdateFoodCountUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/interface/GetOrderDetailUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/interface/GetTotalOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/interface/InsertCartToOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/interface/GetRecentlyViewedFoodsUseCase.kt
  build.gradle
Labels: feature, 광현, 주호

#6 feat: xml 파일 설정
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_cart.xml
  app/src/main/res/drawable/ic_cart_action.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_checked.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_down.xml
  app/src/main/res/drawable/ic_grid.xml
  app/src/main/res/drawable/ic_linear.xml
  app/src/main/res/drawable/ic_reload.xml
  app/src/main/res/drawable/ic_right.xml
  app/src/main/res/drawable/ic_unchecked.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/ic_user_action.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature, ui, 광현

#10 ui: fragment tag를 추출 후 관리
  app/src/main/res/layout/fragment_best.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/layout/fragment_soup.xml
  app/src/main/res/values/strings.xml
Labels: ui, 광현, refactor, 주호

#12 feat: remote dto 생성
  app/src/main/java/com/woowa/banchan/data/remote/dto/BestFood.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/BestFoodCategory.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/DetailItem.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/Food.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/FoodDetail.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/FoodItem.kt
Labels: feature, 광현, 주호

#21 Feature/toobar custom
  app/src/main/java/com/woowa/banchan/ui/common/custom/CustomToolbar.kt
  app/src/main/res/drawable/ic_dark_dot.xml
  app/src/main/res/layout/view_tool_bar_custom.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: feature, ui, 주호

#26 feat: Best 화면 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/data/remote/datasource/food/FoodDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/FoodItem.kt
  app/src/main/java/com/woowa/banchan/data/remote/repository/FoodRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/repository/FoodRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetBestFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetBestFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/common/uistate/UiState.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeActivity.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestViewModel.kt
  app/src/main/java/com/woowa/banchan/utils/Toast.kt
  app/src/main/res/layout/fragment_best.xml
  app/src/main/res/layout/item_best_header.xml
  app/src/main/res/layout/item_best_recyclerview.xml
  app/src/main/res/layout/item_home.xml
  build.gradle
Labels: feature, ui, 광현

#29 refactor: uiState 제네릭 변환
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetBestFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetBestFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/common/uistate/UiState.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestViewModel.kt
Labels: refactor, 주호, fix

#31 refactor: local api 추가 및 수정
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/DeleteCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/InsertCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/UpdateCartCheckStateUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/UpdateCartCountUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/interface/GetDetailFoodUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/interface/GetTotalFoodUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/DeleteFoodFromCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetDetailFoodUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/InsertFoodToCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/UpdateFoodCountUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetOrderDetailUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetTotalOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/InsertCartToOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/interface/GetOrderDetailUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/interface/GetTotalOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/interface/InsertCartToOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/inter/GetRecentlyViewedFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/interface/GetRecentlyViewedFoodsUseCase.kt
Labels: 광현, refactor, 주호

#32 feat: Main 화면 구현
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetBestFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/HomeItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeHeaderViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeItemViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeRecyclerViewViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestBindingAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/MainAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/SpinnerAdapter.kt
  app/src/main/java/com/woowa/banchan/utils/RecyclerviewTag.kt
  app/src/main/res/drawable/background_dropdown_menu.xml
  app/src/main/res/drawable/background_spinner.xml
  app/src/main/res/drawable/custom_checkbox.xml
  app/src/main/res/drawable/ic_grid_checked.xml
  app/src/main/res/drawable/ic_grid_unchecked.xml
  app/src/main/res/drawable/ic_linear_checked.xml
  app/src/main/res/drawable/ic_linear_unchecked.xml
  app/src/main/res/drawable/selector_grid.xml
  app/src/main/res/drawable/selector_linear.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/item_home_header.xml
  app/src/main/res/layout/item_main_header.xml
  app/src/main/res/layout/item_main_linear.xml
  app/src/main/res/layout/item_recyclerview.xml
  app/src/main/res/layout/spinner_content.xml
  app/src/main/res/layout/spinner_title.xml
  app/src/main/res/values/dimens.xml
Labels: feature, ui, 광현

#38 feat: cart recycler view btn callback 기능 구현
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartFooterBtnViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CheckHeaderViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentPreviewViewHolder.kt
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/layout/item_recent_preview.xml
Labels: feature, 주호

#44 feat: Main 화면 구현
  app/src/main/java/com/woowa/banchan/data/remote/datasource/food/FoodDataSource.kt
  app/src/main/java/com/woowa/banchan/data/remote/datasource/food/FoodDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/BestFood.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/BestFoodCategory.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/BestFoodCategoryDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/BestFoodDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/DetailItemDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/FoodDetail.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/FoodDetailDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/FoodDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/FoodItem.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/FoodItemDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/repository/FoodRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/remote/service/BanchanService.kt
  app/src/main/java/com/woowa/banchan/domain/model/BestFoodCategory.kt
  app/src/main/java/com/woowa/banchan/domain/model/DetailItem.kt
  app/src/main/java/com/woowa/banchan/domain/model/FoodDetail.kt
  app/src/main/java/com/woowa/banchan/domain/model/FoodItem.kt
  app/src/main/java/com/woowa/banchan/domain/repository/FoodRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetBestFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetBestFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/common/viewutils/TextViewUtil.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/HomeRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeItemViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeRecyclerViewViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/viewholder/BestHeaderViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/MainRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/SpinnerAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/viewholder/MainHeaderViewHolder.kt
  app/src/main/java/com/woowa/banchan/utils/MoneyUtil.kt
  app/src/main/res/layout/item_best_header.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/item_main_linear.xml
  app/src/main/res/layout/spinner_title.xml
Labels: feature, ui, 광현

#47 feat: order list 화면 구현하기
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderDto.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/DataBaseModule.kt
  app/src/main/java/com/woowa/banchan/di/DataSourceModule.kt
  app/src/main/java/com/woowa/banchan/di/RepositoryModule.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/model/Order.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetTotalOrderUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetTotalOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentItemViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/cart/recent/adapter/RecentRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/common/viewutils/TextViewUtil.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderFragment.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/order/adapter/OrderRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/order/adapter/viewholder/OrderViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailFragment.kt
  app/src/main/java/com/woowa/banchan/utils/Toast.kt
  app/src/main/res/drawable/background_order_item.xml
  app/src/main/res/layout/activity_order.xml
  app/src/main/res/layout/activity_order_detail.xml
  app/src/main/res/layout/fragment_order.xml
  app/src/main/res/layout/fragment_order_detail.xml
  app/src/main/res/layout/item_order.xml
  app/src/main/res/values/colors.xml
Labels: feature, ui, 주호

#51 feat: order detail 화면 구현하기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderItemDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderItemDto.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/DataBaseModule.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/model/OrderItem.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetOrderDetailUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetOrderDetailUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetTotalOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailRVTag.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/OrderDetailRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/viewholder/OrderDetailHeaderViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/viewholder/OrderDetailViewHolder.kt
  app/src/main/res/layout/activity_order_detail.xml
  app/src/main/res/layout/item_order_detail.xml
  app/src/main/res/layout/item_order_detail_header.xml
  app/src/main/res/values/strings.xml
Labels: feature, ui, 주호

#48 feat: Detail 화면 디자인
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/data/remote/datasource/food/FoodDataSource.kt
  app/src/main/java/com/woowa/banchan/data/remote/datasource/food/FoodDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/DetailItemDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/dto/FoodDetailDto.kt
  app/src/main/java/com/woowa/banchan/data/remote/repository/FoodRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/remote/service/BanchanService.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/model/DetailItem.kt
  app/src/main/java/com/woowa/banchan/domain/repository/FoodRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetDetailFoodUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetDetailFoodUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/common/viewutils/TextViewUtil.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/detail/adapter/DetailRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/detail/adapter/DetailVPAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/detail/viewholder/DetailRVViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/detail/viewholder/DetailVPViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/HomeRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeItemViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/MainRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/adapter/SoupRVAdapter.kt
  app/src/main/res/drawable/circle_btn_background.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/item_main_linear.xml
  app/src/main/res/layout/item_recent.xml
  app/src/main/res/layout/item_rv_detail.xml
  app/src/main/res/layout/item_vp_detail.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: feature, ui, 광현

#53 feat: insert Cart 기능 구현
  app/build.gradle
  app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/CartDto.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderDto.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/model/FoodItem.kt
  app/src/main/java/com/woowa/banchan/domain/repository/CartRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/InsertCartUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/InsertCartUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddFragment.kt
  app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/detail/viewholder/DetailVPViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/HomeRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeItemViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/MainRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/adapter/SoupRVAdapter.kt
  app/src/main/res/drawable/background_bottomsheet.xml
  app/src/main/res/layout/fragment_cart_add.xml
  app/src/main/res/values-night-v31/themes.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature, ui, 광현

#54 feat: Side 화면 구현
  app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/SoupSideRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/viewholder/SoupSideHeaderViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/side/SideViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/layout/item_rv_detail.xml
  app/src/main/res/values/strings.xml
Labels: feature, ui, 광현

#59 fix: Order 화면 데이터 표시 버그 해결
  app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderActivity.kt
Labels: 주호, fix

#60 feat: order detail 데이터 로드 및 order 데이터 갱신 기능
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetEachOrderUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetEachOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/OrderDetailRVAdapter.kt
  app/src/main/res/layout/item_order_detail.xml
Labels: feature, 주호, fix

#62 fix: Cart to OrderItem 삽입 시 에러 해결
  app/src/main/java/com/woowa/banchan/data/local/entity/CartDto.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/OrderItemDto.kt
Labels: 주호, fix

#67 feat: Recently Viewed Products 아이템 추가 기능 구현 및 버그 수정
  app/src/main/java/com/woowa/banchan/data/local/dao/RecentDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/RecentDto.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/di/UseCaseModule.kt
  app/src/main/java/com/woowa/banchan/domain/model/DetailItem.kt
  app/src/main/java/com/woowa/banchan/domain/repository/RecentRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/InsertRecentlyViewedFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/inter/InsertRecentlyViewedFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentPreviewViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/utils/DateUtil.kt
Labels: feature, 주호, fix

#65 fix: Cart 버그 장바구니 변경사항 및 상품이 비었습니다 아이템 버그 해결
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
Labels: 주호, fix

#69 feat: Cart 수량 변경을 키보드 입력받을 수 있도록 구현
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
  app/src/main/res/layout/item_cart.xml
Labels: feature, 주호

#72 refactor: Recent Table nPrice nullable 처리
  app/src/main/java/com/woowa/banchan/data/local/entity/RecentDto.kt
  app/src/main/java/com/woowa/banchan/domain/model/DetailItem.kt
  app/src/main/java/com/woowa/banchan/domain/model/Recent.kt
Labels: refactor, 주호

#73 feat: Cart Icon 기능 구현
  app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/repository/CartRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/DeleteCartUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/DeleteCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetBestFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/common/viewutils/ImageViewUtil.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeItemViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/side/SideViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupViewModel.kt
  app/src/main/res/drawable/background_circle_accent.xml
  app/src/main/res/drawable/background_circle_white.xml
  app/src/main/res/drawable/ic_check_white.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_cart_add.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/item_main_linear.xml
  app/src/main/res/layout/item_recent.xml
Labels: feature, ui, 광현, refactor

#82 ui: App 로고 추가
  app/src/main/AndroidManifest.xml
  app/src/main/ic_app_logo-playstore.png
  app/src/main/ic_app_logo_accent-playstore.png
  app/src/main/java/com/woowa/banchan/ui/common/viewutils/ImageViewUtil.kt
  app/src/main/res/drawable/background_splash_screen.xml
  app/src/main/res/drawable/img_placeholder.png
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo_accent.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo_accent_round.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_app_logo.png
  app/src/main/res/mipmap-hdpi/ic_app_logo_accent.png
  app/src/main/res/mipmap-hdpi/ic_app_logo_accent_foreground.png
  app/src/main/res/mipmap-hdpi/ic_app_logo_accent_round.png
  app/src/main/res/mipmap-hdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-hdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-mdpi/ic_app_logo.png
  app/src/main/res/mipmap-mdpi/ic_app_logo_accent.png
  app/src/main/res/mipmap-mdpi/ic_app_logo_accent_foreground.png
  app/src/main/res/mipmap-mdpi/ic_app_logo_accent_round.png
  app/src/main/res/mipmap-mdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-mdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo_accent.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo_accent_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo_accent_round.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_accent.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_accent_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_accent_round.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_accent.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_accent_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_accent_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_round.png
  app/src/main/res/values-night-v31/themes.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/ic_app_logo_accent_background.xml
  app/src/main/res/values/ic_app_logo_background.xml
Labels: ui, 광현

#89 fix: 배송 남은 시간 버그 수정
  app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/viewholder/OrderDetailHeaderViewHolder.kt
Labels: 주호, fix

#91 feat: Cart 버그 수정 및 전체 선택 기능 구현
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CheckHeaderViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/common/popup/CartCompleteFragment.kt
  app/src/main/res/layout/item_cart_check_header.xml
Labels: feature, 주호, fix

#93 feat: Recent 기능(클릭 시 디테일 이동 및 장바구니 아이콘) 구현 및 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/entity/RecentDto.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/model/Recent.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/RecentPreviewRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentItemViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/RecentPreviewViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/recent/adapter/RecentRVAdapter.kt
  app/src/main/res/layout/item_recent.xml
Labels: feature, 주호

#94 refactor: 데이터 로드하는 함수의 job 반환형을 Unit으로 변환
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailViewModel.kt
Labels: refactor, 주호

#90 feat: Detail 기능 추가
  app/src/main/java/com/woowa/banchan/domain/model/DetailItem.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/UpdateCartUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/UpdateCartUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/common/event/SingleEvent.kt
  app/src/main/java/com/woowa/banchan/ui/detail/CartUpdateFragment.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseViewModel.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_cart_update.xml
  app/src/main/res/values/strings.xml
Labels: feature, 광현

#97 fix: Food Item 갱신 버그 수정
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeRVTag.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/HomeRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/SoupSideRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/viewholder/SoupSideHeaderViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeItemViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/viewholder/HomeRecyclerViewViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/MainRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/viewholder/MainHeaderViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/item_main_linear.xml
Labels: feature, 광현, fix

#100 feat: Best Tab 깜빡거림 현상 제거
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestItemAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/viewholder/BestHeaderViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/viewholder/BestItemViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/viewholder/BestViewHolder.kt
  app/src/main/res/layout/item_best.xml
  app/src/main/res/layout/item_best_header.xml
  app/src/main/res/layout/item_best_recyclerview.xml
Labels: 광현, refactor, fix

#101 fix: Horizontal Scroll 중첩 문제 해결
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/viewholder/BestViewHolder.kt
Labels: 광현, fix

#103 fix: 카트 화면 깜박임 및 전체 선택 주문 오류 버그 수정
  app/src/main/java/com/woowa/banchan/domain/model/Cart.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CheckHeaderViewHolder.kt
Labels: 주호, fix

#106 Feature/testcase
  app/build.gradle
  app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderItemDao.kt
  app/src/test/java/com/woowa/banchan/data/local/dao/CartDaoTest.kt
  app/src/test/java/com/woowa/banchan/data/local/dao/OrderDaoTest.kt
  app/src/test/java/com/woowa/banchan/data/local/dao/OrderItemDaoTest.kt
  app/src/test/java/com/woowa/banchan/data/local/dao/RecentDaoTest.kt
  app/src/test/java/com/woowa/banchan/data/local/datasource/CartDataSourceTest.kt
  app/src/test/java/com/woowa/banchan/data/local/datasource/OrderDataSourceTest.kt
  app/src/test/java/com/woowa/banchan/data/local/datasource/RecentDataSourceTest.kt
  app/src/test/java/com/woowa/banchan/data/repository/cart/CartRepositoryTest.kt
  app/src/test/java/com/woowa/banchan/data/repository/cart/FakeCartDataSource.kt
  app/src/test/java/com/woowa/banchan/data/repository/food/FoodRepositoryTest.kt
  app/src/test/java/com/woowa/banchan/data/repository/order/OrderRepositoryTest.kt
  app/src/test/java/com/woowa/banchan/data/repository/recent/RecentRepositoryTest.kt
  build.gradle
Labels: feature, 광현, 주호

#108 feat: loading 추가
  app/src/main/java/com/woowa/banchan/ui/common/viewutils/LoadingUtil.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_best.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/layout/fragment_soup.xml
Labels: feature, ui, 주호

#109 refactor: clickEvent ViewModel로 이전
  app/src/main/java/com/woowa/banchan/ui/cart/CartActivity.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddFragment.kt
  app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/common/popup/CartCompleteFragment.kt
  app/src/main/java/com/woowa/banchan/ui/common/popup/CartCompleteViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/detail/CartUpdateFragment.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeActivity.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/viewholder/BestViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/order/adapter/OrderRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailViewModel.kt
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_order.xml
  app/src/main/res/layout/activity_order_detail.xml
  app/src/main/res/layout/fragment_cart_add.xml
  app/src/main/res/layout/fragment_cart_complete.xml
Labels: 광현, refactor

#113 Feat: 에러 버튼 기능 추가
  app/src/main/java/com/woowa/banchan/ui/common/custom/CustomErrorView.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/side/SideViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupViewModel.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_best.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/layout/fragment_soup.xml
Labels: feature, 주호

#114 feat: Cart와 Recent Flow로 연결
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/GetRecentlyViewedFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/recent/adapter/RecentGridItemViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/cart/recent/adapter/RecentRVAdapter.kt
  app/src/main/res/layout/fragment_recent.xml
  app/src/main/res/layout/item_recent_grid.xml
Labels: feature, 광현, refactor

#115 refactor: usecase UiState 타입을 Result타입으로 변환
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/remote/repository/FoodRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/repository/CartRepository.kt
  app/src/main/java/com/woowa/banchan/domain/repository/FoodRepository.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
  app/src/main/java/com/woowa/banchan/domain/repository/RecentRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/DeleteCartUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/GetCartCountUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/GetCartListUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/InsertCartUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/UpdateCartUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/DeleteCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/GetCartCountUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/GetCartListUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/InsertCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/UpdateCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetBestFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetDetailFoodUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/GetFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetBestFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetDetailFoodUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/food/inter/GetFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetEachOrderUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetOrderDetailUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetOrderStateUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetTotalOrderUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/InsertCartToOrderUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/UpdateOrderUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetEachOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetOrderDetailUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetOrderStateUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetTotalOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/InsertCartToOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/UpdateOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/GetRecentlyViewedFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/InsertRecentlyViewedFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/inter/GetRecentlyViewedFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/inter/InsertRecentlyViewedFoodsUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/worker/OrderWorker.kt
Labels: refactor, 주호

#123 fix: DB 버그 수정
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
Labels: 주호, fix

#125 refactor: String 하드코딩 문자열 추출
  app/src/main/java/com/woowa/banchan/ui/cart/CartActivity.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/common/viewutils/TextViewUtil.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeActivity.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/SoupSideRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/MainRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/SpinnerAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderActivity.kt
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_cart_add.xml
  app/src/main/res/layout/fragment_cart_complete.xml
  app/src/main/res/layout/fragment_cart_update.xml
  app/src/main/res/layout/item_cart_button_footer.xml
  app/src/main/res/layout/item_cart_check_header.xml
  app/src/main/res/layout/item_order.xml
  app/src/main/res/layout/item_order_detail_header.xml
  app/src/main/res/layout/item_recent_preview.xml
  app/src/main/res/layout/item_total_price.xml
  app/src/main/res/layout/view_tool_bar_custom.xml
  app/src/main/res/values/strings.xml
Labels: refactor, 주호

#126 refactor: 로딩 시 화면 끊김 대응
  app/src/main/java/com/woowa/banchan/ui/home/HomeActivity.kt
Labels: 주호, fix

#129 feat: WorkManager와 AlarmManager를 이용해 알림 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowa/banchan/data/local/dao/OrderItemDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/order/OrderDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/repository/OrderRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetEachOrderUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/GetOrderDetailUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/InsertCartToOrderUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetEachOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/GetOrderDetailUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/order/inter/InsertCartToOrderUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/common/key/Key.kt
  app/src/main/java/com/woowa/banchan/ui/common/receiver/OrderReceiver.kt
  app/src/main/java/com/woowa/banchan/ui/common/viewutils/TextViewUtil.kt
  app/src/main/java/com/woowa/banchan/ui/common/worker/OrderWorker.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeRVTag.kt
  app/src/main/java/com/woowa/banchan/ui/order/OrderActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailActivity.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/OrderDetailRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/viewholder/OrderDetailHeaderViewHolder.kt
  app/src/main/res/layout/activity_order_detail.xml
  app/src/main/res/layout/item_order_detail_header.xml
  app/src/main/res/values/strings.xml
Labels: feature, 광현, fix

#127 refactor: activity 스택관리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
Labels: 주호, fix

#131 feat: CartFragment 로직 수정
  app/src/main/java/com/woowa/banchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/cart/CartDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/repository/CartRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/DeleteCartUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/UpdateCartUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/DeleteCartUseCase.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/cart/inter/UpdateCartUseCase.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/CartFragment.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/CartRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/common/recyclerview/RVItem.kt
  app/src/main/java/com/woowa/banchan/ui/common/viewutils/TextViewUtil.kt
  app/src/main/java/com/woowa/banchan/ui/home/HomeRVTag.kt
  app/src/main/java/com/woowa/banchan/ui/home/adapter/soupside/SoupSideRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/adapter/BestRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/adapter/MainRVAdapter.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/adapter/OrderDetailRVAdapter.kt
  app/src/main/res/layout/activity_order_detail.xml
  app/src/main/res/values/strings.xml
Labels: feature, 광현, refactor, fix

#135 fix: recent에서 카트 추가할 때 장바구니 화면이 변화되지 않는 버그 수정
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
Labels: 주호, fix

#134 refactor: 아이콘 배지 크기 변경
  app/src/main/java/com/woowa/banchan/ui/common/custom/CustomToolbar.kt
  app/src/main/java/com/woowa/banchan/ui/common/viewutils/ImageViewUtil.kt
  app/src/main/java/com/woowa/banchan/ui/order/detail/OrderDetailViewModel.kt
  app/src/main/res/drawable/placeholder.xml
  app/src/main/res/layout/view_tool_bar_custom.xml
  app/src/main/res/values/styles.xml
Labels: ui, 광현, refactor

#139 fix: ViewModel DataBinding 추가
  app/src/main/java/com/woowa/banchan/ui/home/HomeBaseFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/main/MainFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/side/SideFragment.kt
  app/src/main/java/com/woowa/banchan/ui/home/soup/SoupFragment.kt
Labels: 광현, fix

#143 fix: FoodItem Count 범위 수정
  app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddFragment.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
Labels: 광현, fix

#151 fix: cart 화면 수량 버그 수정
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
Labels: 주호, fix

#153 refactor: 최근 조회 목록 갱신
  app/src/main/java/com/woowa/banchan/data/local/dao/RecentDao.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSource.kt
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
  app/src/main/java/com/woowa/banchan/data/local/repository/RecentRepositoryImpl.kt
  app/src/main/java/com/woowa/banchan/domain/repository/RecentRepository.kt
  app/src/main/java/com/woowa/banchan/domain/usecase/recent/GetRecentlyViewedFoodsUseCaseImpl.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartActivity.kt
  app/src/main/java/com/woowa/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
  app/src/main/java/com/woowa/banchan/ui/cart/recent/RecentFragment.kt
  app/src/main/java/com/woowa/banchan/ui/common/bottomsheet/CartAddFragment.kt
  app/src/main/java/com/woowa/banchan/ui/common/custom/CustomToolbar.kt
  app/src/main/java/com/woowa/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/woowa/banchan/utils/DateUtil.kt
Labels: 광현, refactor, fix

#154 fix: cart에 빈 상품이 담기던 버그 수정
  app/src/main/java/com/woowa/banchan/ui/cart/cart/adapter/viewholder/CartContentViewHolder.kt
Labels: 광현, fix

#157 fix: Recent가 MainThread에서 지워지던 버그 수정
  app/src/main/java/com/woowa/banchan/data/local/datasource/recent/RecentDataSourceImpl.kt
Labels: 광현, fix
